### ISSUE TITLE
possible to use (angularjs) ng-repeat in templates?

### ISSUE THREAD

**Issue by scottnath** [colynb/gulp-swig#23]
I am attempting to build an html pattern library which will be used by AngularJS to build templates. The templates should be able to use default data (supplied in the file via Yaml Front-Matter) to build the templates.

Is it possible to use ng-repeat in my templates when gulp converts the data via gulp-data and sends it into gulp-swig?

## example

[github repo: gulp-swig-ng-repeat](https://github.com/scottnath/gulp-swig-ng-repeat)

### gulpfile.js

```
'use strict';
var gulp = require('gulp');
var frontMatter = require('front-matter');
var swig = require('gulp-swig');
var data = require('gulp-data');

/*
  Get data via front matter
*/
gulp.task('fm-test', function() {
  return gulp.src('./patterns/**/*.html')
    .pipe(data(function(file) {
      var content = frontMatter(String(file.contents));
      file.contents = new Buffer(content.body);
      console.log(content.attributes)
      return content.attributes;
    }))
    .pipe(swig())
    .pipe(gulp.dest('build'));
});
```

### ng-repeat html template

```
---
something: thing
levelOneNavObject:
  mainItemOne:
    title: main item one
    url: google.com
  mainItemTwo:
    title: main item two
    url: yahoo.com
    levelTwoNavObject:
      subItemOne:
        title: sub item one
        url: yahoo.com/1
      subItemTwo:
        title: sub item two
        url: yahoo.com/2
      subItemThree:
        title: sub item three
        url: yahoo.com/3
  mainItemThree:
    title: main item three
    url: bing.com
---
<p>{{something}}</p>
<p>{{levelOneNavObject.mainItemOne.title}}</p>
<nav class="navigation--MAIN">
  <ul class="navigation--primary">
    <li class="navigation--primary-list-item" ng-repeat="mains in levelOneNavObject"><a href="http://{{mains.url}}">{{mains.title}}</a></li>
  </ul>

</nav>

```

thanks for any help,
Scott
